# Generated by Django 3.1.4 on 2021-02-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in1', models.PositiveIntegerField()),
                ('in2', models.PositiveIntegerField()),
                ('out', models.TextField(max_length=400)),
            ],
        ),
    ]
